### ISSUE TITLE
I don't know how to choose a matching bin file for a mapgeo, could you please help me

### ISSUE THREAD

**Issue by wqaetly** [FrankTheBoxMonster/LoL-MAPGEO-Converter#1]
I don't know how to choose a matching bin file for a mapgeo, could you please help me

**Comment by wqaetly** [comment]
it usually shows this。。。
![QQ截图20190907214647](https://user-images.githubusercontent.com/35335061/64475735-24ea4a80-d1b9-11e9-93d6-fe0fe0a28d96.png)

**Comment by FrankTheBoxMonster** [comment]
Sorry, my notifications were not working and I didn't see this until just now, two months later.  Do you still need help?

What I did to find matching files was to see what materials the program said that it could not find and then have my computer search for bin files from the same wad as the mapgeo that also contained that missing material name, and then trying those files one by one until you find one that isn't missing any materials.

**Comment by wqaetly** [comment]
Thank you very much. I'll try






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"FrankTheBoxMonster"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月9日(星期六) 上午6:35
收件人:&nbsp;"FrankTheBoxMonster/LoL-MAPGEO-Converter"<LoL-MAPGEO-Converter@noreply.github.com&gt;;
抄送:&nbsp;"烟雨迷离半世殇"<1778139321@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [FrankTheBoxMonster/LoL-MAPGEO-Converter] I don't know how to choose a matching bin file for a mapgeo, could you please help me (#1)




Sorry, my notifications were not working and I didn't see this until just now, two months later.  Do you still need help?
 
What I did to find matching files was to see what materials the program said that it could not find and then have my computer search for bin files from the same wad as the mapgeo that also contained that missing material name, and then trying those files one by one until you find one that isn't missing any materials.
