### ISSUE TITLE
Can't import obj into blender

### ISSUE THREAD

**Issue by Supora** [FrankTheBoxMonster/LoL-MAPGEO-Converter#2]
I got this error
```
Total loading time:  00 minutes 00 seconds
(  0.0000 sec |   0.0000 sec) Importing OBJ 'E:\\Maps\\DATA\\maps\\MapGeometry\\SR\\Base_SRX.Layer0.obj'...
  (  0.0000 sec |   0.0000 sec) Parsing OBJ file...
Progress:   0.00%

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_obj\__init__.py", line 148, in execute
    return import_obj.load(context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_obj\import_obj.py", line 1074, in load
    context_multi_line = handle_vec(line_start, context_multi_line, line_split, b'vn', verts_nor, vec, 3)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_obj\import_obj.py", line 984, in handle_vec
    vec[:] = [float_func(v) for v in line_split[1:]]
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_obj\import_obj.py", line 984, in <listcomp>
    vec[:] = [float_func(v) for v in line_split[1:]]
ValueError: could not convert string to float: b'=5\xa0G8A;>'

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by Supora** [comment]
Tried both 2.8 and 2.79 blender versions

**Comment by FrankTheBoxMonster** [comment]
Other people have gotten it to work in Blender 2.80 just fine, don't know about pre-2.80 but I doubt that would matter.  I only use Maya, so can only fix problems if it has them in Maya.  I've never used Blender and don't know anything about it, and that error message doesn't give away anything obvious, so I have no idea what might be going wrong for you but it isn't happening to the other people that I've had test it.

**Comment by Supora** [comment]
maya 2017 gives that error
`file -import -type "OBJ" -gr  -ignoreVersion -ra true -mergeNamespacesOnClash false -rpr "Base_SRX_Layer1" -options "mo=1;lo=0" -loadReferenceDepth "none" "E:/Maps/DATA/maps/MapGeometry/SR/Base_SRX.Layer1.obj";
// Error: line 0: Your OBJ file contains a line which is too long to be parsed. Please edit your obj file. // 
// File read in  0.32 seconds.
// Error: line 0: Error reading file. //`

**Comment by FrankTheBoxMonster** [comment]
You must be doing something wrong or have some setting that's messing with how the file is being read or written, or maybe aren't even using the correct file.  The longest line in the .obj file when I use the converter is 65 characters, so it's definitely not supposed to be anywhere close to being too long.

**Comment by Supora** [comment]
So my steps were: get Base_SRX.mapgeo and Base_SRX.materials.bin and drag and drop them on LoL-MAPGEO-Converter.exe
then import it to any 3d software

**Comment by FrankTheBoxMonster** [comment]
Can you upload and send me the .obj file that it's giving you?

**Comment by Supora** [comment]
actually any file that I get gives me same results
[https://mega.nz/#!nS5U1QSJ!ItCPMw8DNlLfDwnJodj6fQf_jrQs77Bwk-toMJoQdlQ](one sr layer, other layers give me same errors)

**Comment by FrankTheBoxMonster** [comment]
Can you try using this version now? 

[LoLMapGeoConverter_maybefixed.zip](https://github.com/FrankTheBoxMonster/LoL-MAPGEO-Converter/files/4049275/LoLMapGeoConverter_maybefixed.zip)

Your computer is set to a region that writes numbers as "123,456" instead of "123.456", with a comma as the decimal separator.  The .obj importers want a period, but the converter was just using whatever your computer is set to.  This version should force the converter to always write them with periods (your computer settings won't be affected).

**Comment by Supora** [comment]
blender 2.8 get things in
will try on maya and 2.79 later but I think it will be okay
