### ISSUE TITLE
Lightmap support?

### ISSUE THREAD

**Issue by TheKillerey** [FrankTheBoxMonster/LoL-MAPGEO-Converter#4]
No issues but do you think your able to add lightmaps to the maps using ambient color for it? This can help a bit to understand the light stuff on the map.

**Comment by TheKillerey** [comment]
Hmm idk if the models have uvs specially for the lightmaps. Or the textures are resized.

**Comment by FrankTheBoxMonster** [comment]
Lightmaps use separate UVs and they have coordinate offsets and scale multipliers.  The offset/scale is simple enough to solve but the .OBJ file format only supports one UV set so I can't add both, and it isn't worth it to me to completely rewrite the exporter for something so minor.

**Comment by TheKillerey** [comment]
Its okay just an idea ^^ but thanks for it
