### ISSUE TITLE
Question about the textures

### ISSUE THREAD

**Issue by drakan08** [FrankTheBoxMonster/LoL-MAPGEO-Converter#5]
Im not sure how the textures suppose to work with the program, i did as it was written a drop both the .mapgeo and the .materials.bin into the .exe file but i get these results:

The mesh textures seems to have a different names from the .dds files i saw around, does the program suppose to gatter the textures?

It seems to say that it was no able to find the textures

![1](https://user-images.githubusercontent.com/26861121/91677958-aa79af80-eb1a-11ea-9e93-89da0d9376ff.png)
![2](https://user-images.githubusercontent.com/26861121/91677960-ab124600-eb1a-11ea-810a-6a8cc97f55ab.png)
![3](https://user-images.githubusercontent.com/26861121/91677963-ac437300-eb1a-11ea-8bd5-33c84a9577ea.png)
![4](https://user-images.githubusercontent.com/26861121/91677951-a483ce80-eb1a-11ea-85b0-ea79d6940a26.jpg)

**Comment by FrankTheBoxMonster** [comment]
The "found 0 baked paint texture names" is a different kind of texture than what SR uses, so that's not an error there.

The converter doesn't find texture files on its own, it just tells an .OBJ viewer what to look for, where the exact rules can vary based on the application.  I've only tested with Maya, not Blender, but for Maya the folders need to look like this:
```
/whatever folder you have things in/
    srx.mapgeo
    srx.materials.bin
    srx.obj
    srx.mtl
    /textures/
        /ASSETS/
            /Maps/
                /KitPieces/
                    /SRX/
                        /textures/
                            Base_BotLane_Ground_D.SRX_EnvArt.dds
                            Base_BotLane_Ground_E.SRX_EnvArt.dds
                            etc.
```
The "textures" folder just needs to be next to the .OBJ/.MTL files and you just throw the extracted .WAD files into there and Maya figures it out, if Blender can't then I'm not sure how to fix that.

**Comment by drakan08** [comment]
Having the /textures/ folder next to the .mapgeo as you mentioned did the trick, thanks!

![Sin título](https://user-images.githubusercontent.com/26861121/91680625-29beb180-eb22-11ea-9b25-dde96058da97.jpg)

**Comment by drakan08** [comment]
> 
> 
> The "found 0 baked paint texture names" is a different kind of texture than what SR uses, so that's not an error there.
> 
> The converter doesn't find texture files on its own, it just tells an .OBJ viewer what to look for, where the exact rules can vary based on the application. I've only tested with Maya, not Blender, but for Maya the folders need to look like this:
> 
> ```
> /whatever folder you have things in/
>     srx.mapgeo
>     srx.materials.bin
>     srx.obj
>     srx.mtl
>     /textures/
>         /ASSETS/
>             /Maps/
>                 /KitPieces/
>                     /SRX/
>                         /textures/
>                             Base_BotLane_Ground_D.SRX_EnvArt.dds
>                             Base_BotLane_Ground_E.SRX_EnvArt.dds
>                             etc.
> ```
> 
> The "textures" folder just needs to be next to the .OBJ/.MTL files and you just throw the extracted .WAD files into there and Maya figures it out, if Blender can't then I'm not sure how to fix that.

By the way do you know in which wad file are the nexus,turret and inhibitor for both SR and Aram maps?
