### ISSUE TITLE
Which Texutures folder to choose

### ISSUE THREAD

**Issue by aresfor** [FrankTheBoxMonster/LoL-MAPGEO-Converter#7]
There are too many.Mapgeo files.  I knew that to extract a textured map I needed to put the textures folder next to the.obj file, but I didn't know which textures folder to select

**This is the.mapgeo file and the.bin file that I used**

![QQ图片20210927192440](https://user-images.githubusercontent.com/62842879/134899885-78d320b8-c8af-48b8-80e5-cd6f07023343.png)

**The Textures folder is this one**

![QQ图片20210927192714](https://user-images.githubusercontent.com/62842879/134899951-c2fbbe2d-ce55-4543-a2a3-4f4fa7c22799.png)

**Importing a model file from the first image into Blender is like this, I need your help** 

![QQ图片20210927192728](https://user-images.githubusercontent.com/62842879/134900042-94bcbd9e-3eba-4b1c-b01e-82a35dc5ccb9.png)

**It would help me a lot if you knew some solutions,thanks**

**Comment by FrankTheBoxMonster** [comment]
The texture paths are somewhat specific depending on what program you are opening the file in.

Some programs would be fine with something like this:
```
base_srx.Layer0.obj
base_srx.Layer0.mtl
textures
    grnd_terrain_a.dds
    grnd_terrain_b.dds
    grnd_terrain_c.dds
    fire_north_bluecamp_ground_a.dds
```

Some programs would instead want something like this:
```
base_srx.Layer0.obj
base_srx.Layer0.mtl
textures
    assets
        maps
            kitpieces
                summoners_rift
                    textures
                        grnd_terrain_a.dds
                        grnd_terrain_b.dds
                        grnd_terrain_c.dds
                srx
                    textures
                        fire_north_bluecamp_ground_a.dds
```


I'm not sure which Blender prefers, but the easiest solution is usually to copy the entire .wad extraction into the textures folder.  If Blender doesn't need the exact folders then you can instead search for all .dds files and copy those into the textures folder instead.

**Comment by aresfor** [comment]
I tried the second method and it worked in Blender, although all materials had a highlight of 1, but a simple Python script can fix this.  Even though this is a very basic map.Thank you,Frank
